[project]
name = "mercari-mcp"
version = "0.1.0"
description = "A FastMCP server to search Mercari Japan."
requires-python = ">=3.10"
readme = "README.md"
license = "MIT"

dependencies = [
    "fastmcp>=2.0.0",
    "mercari==2.2.1",
    "pydantic>=2.0",
    "cffi>=1.14.6",
]

[tool.setuptools]
py-modules = ["server", "check_server"]
